### ISSUE TITLE
[Epic] Option 4b PoC: SDK

### ISSUE THREAD

**Issue by askolesov** [cheqd/cheqd-sdk#5]
Requirements:
- cosmos-rust should be used (https://github.com/cosmos/cosmos-rust)

PoA:
- Tx:
  - [x] Implement transaction encoding
  - [x] Implement transaction signing
  - [x] Implement transaction sending
  - [x] Implement protobuff generation for non default transactions
- Query
  - [x] Implement queries encoding
  - [x] Implement queries sending
  - [ ] Add proof validation
- Libindy API
  - [x] Cosmos keys management (https://github.com/verim-id/verim-cosmos-sdk/issues/4)
  - [x] Transactions
  - [x] Queries
  - [x] Pool management
- Wrappers
  - [x] Rust
-  CLI commands
   - [ ] Cosmos keys management (https://github.com/verim-id/verim-cosmos-sdk/issues/4)
   - [ ] Transactions
   - [ ] Queries
   - [ ] Pool management

Deprecated:
- Add support for key imports (https://github.com/verim-id/verim-cosmos-sdk/issues/2)
